### PR TITLE
🚩PR: CTRL + Click togggles selection of action block

### LINKED ISSUE #665: Ctrl + Click should select actionblocks

### PR DESCRIPTION
**Pull request by elsoazemelet**
Closes #665

### CODE REVIEW

**Comment by elsoazemelet** [comment]
- [x] configuration.svelte should not know about ctrl key

**Comment by narayb** [comment]
Works as intended, but there are weird interactions when the user interacts with the blocks while holding the Ctrl key.

ctrl_controls_many_things

**Comment by elsoazemelet** [comment]
> Works as intended, but there are weird interactions when the user interacts with the blocks while holding the Ctrl key.
> 
> ctrl_controls_many_things [ ctrl_controls_many_things ](https://private-user-images.githubusercontent.com/74784772/319561772-38d1aa00-9664-43be-8a9d-42a5b670af77.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzg1NDIsIm5iZiI6MTcxMjIzODI0MiwicGF0aCI6Ii83NDc4NDc3Mi8zMTk1NjE3NzItMzhkMWFhMDAtOTY2NC00M2JlLThhOWQtNDJhNWI2NzBhZjc3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEzNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZjEzZWFjNWJkZjFkNjMxOTNiNThhNWZmNWQzNTdjYjJjN2JiMTk5ZDkxZTQ1ZjkxNWE5NGZhZjUwYjYwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FYPJdV_2NHbWg3puJheZ1NcW_hi5EQShxM4HHEzVQYk) [ ](https://private-user-images.githubusercontent.com/74784772/319561772-38d1aa00-9664-43be-8a9d-42a5b670af77.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzg1NDIsIm5iZiI6MTcxMjIzODI0MiwicGF0aCI6Ii83NDc4NDc3Mi8zMTk1NjE3NzItMzhkMWFhMDAtOTY2NC00M2JlLThhOWQtNDJhNWI2NzBhZjc3LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDEzNDQwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFjZjEzZWFjNWJkZjFkNjMxOTNiNThhNWZmNWQzNTdjYjJjN2JiMTk5ZDkxZTQ1ZjkxNWE5NGZhZjUwYjYwNzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FYPJdV_2NHbWg3puJheZ1NcW_hi5EQShxM4HHEzVQYk)

Fixed in the latest commit

**Comment by SukuWc** [comment]
Right padding of highlight is incorrect 
image

**Comment by elsoazemelet** [comment]
> Right padding of highlight is incorrect image

Fixed in the latest commit

**Pull request merged**
