### PR TITLE
Suggestions now render

### PR DESCRIPTION
**Pull request by elsoazemelet**
image

### CODE REVIEW

**Comment by narayb** [comment]
suggestions
- [x] midi14 dropdown error
- [x] led intensity, after adding block input fields show sytax error and stay red even with correct syntax
- [x] mouse click error on picking option from dropdown
- [x] buttonmode error on picking option from dropdown
- [x] encodermode error on picking option from dropdown
- [x] potmetermode error on picking option from dropdown
- [x] double-clicking fields in loop block throws error
- [x] comment block, clicking text field throws error
- [x] element name block, clicking text field throws error
- [x] clock mode, start, stop: after adding block input fields show sytax error and stay red even with correct syntax
image

**Comment by elsoazemelet** [comment]
> suggestions
> 
> * [x]  midi14 dropdown error
> * [x]  led intensity, after adding block input fields show sytax error and stay red even with correct syntax
> * [x]  mouse click error on picking option from dropdown
> * [x]  buttonmode error on picking option from dropdown
> * [x]  encodermode error on picking option from dropdown
> * [x]  potmetermode error on picking option from dropdown
> * [x]  double-clicking fields in loop block throws error
> * [x]  comment block, clicking text field throws error
> * [x]  element name block, clicking text field throws error
> * [x]  clock mode, start, stop: after adding block input fields show sytax error and stay red even with correct syntax
>   image

Fixed, check it out! :)

**Comment by narayb** [comment]
Fixed!

**Comment by narayb** [comment]
Still fixed!

**Pull request merged**
