### PR TITLE
🚩PR: Fixed crash of stable

### LINKED ISSUE #619: Stable crash

### PR DESCRIPTION
**Pull request by elsoazemelet**
Closes #619 

- Fixed editor crash when connecting 4 modules, then disconnecting them all via plugging the USB out
- Fixed editor crash when adding a virtual module (when no modules are connected)

### CODE REVIEW

**Comment by narayb** [comment]
Tested and crash is still present. Crashes occur when trying to load/save profiles and when trying to clear a module configuration.

**Comment by narayb** [comment]
Previously spotted crashes gone, weird 'undef event' messages spotted in Logger.
kép

**Comment by SukuWc** [comment]
I created test profile that sets 8 of the encoders on EN16 to red. When loading this profile to clean modules I see the following issue:
- Active changes are only detected on one of the modules!
image

**Comment by elsoazemelet** [comment]
> Tested and crash is still present. Crashes occur when trying to load/save profiles and when trying to clear a module configuration.

Fixed in the latest commit.

**Comment by elsoazemelet** [comment]
> Previously spotted crashes gone, weird 'undef event' messages spotted in Logger. kép

Undef event type is fixed, all runtime lua errors are displayed correctly

**Comment by elsoazemelet** [comment]
> I created test profile that sets 8 of the encoders on EN16 to red. When loading this profile to clean modules I see the following issue:
> 
> * Active changes are only detected on one of the modules!
>   image

Fixed in the latest commit. Writebuffer clearing is improved to handle multiple clashing module operations (fast loading to multiple modules), and fixed promise handling. The active changes now displayed properly, no "half" operations are permitted now (this was the cause of the not appearing active changes).

**Comment by SukuWc** [comment]
Active page on UI does not represent module state. When switching page using the map mode button, the page indicator on the UI stays at Page 1. 

I double checked, that this was working in latest release v1.2.48. 

@elsoazemelet please check!

image

**Comment by elsoazemelet** [comment]
TODO:

- [x] Check user_input and corresponding runtime error:

-  Connect second mudule 
-  Select control element on it
- Disconnect second module
- Reconnect second module
- Load profile onto second module

- [x]  Immediate heartbeat should be binded to a developer option, default is false

**Pull request merged**
