### PR TITLE
🚩PR: Added UI for Virtual Module management

### LINKED ISSUE #681: Virtual module add/remove UX from middle pane
Image

### PR DESCRIPTION
**Pull request by elsoazemelet**
Closes #681 

- Changed Text of Virtual Module adder button on module connect dialog
- Changed title of Add Virtual Module modal dialog
- Added feature of virtual module add/remove/change on the grid UI (after adding at least one virtual module)
- The selected virtual module can be removed
- The selected virtual module can be changed
- Other virtual modules can be added from any empty side of a virtual module
- When connecting a physical module, all virtual modules should disappear
- When connecting a physical module, the margin of the modules should be correct (no space should be visible where the module add button is visible on the bottom => between the modules and the page changer buttons)

### CODE REVIEW

**Comment by elsoazemelet** [comment]
- [x] Make add button less prominent
- [x] Remove manual module add from dev settings

**Comment by narayb** [comment]
In the dialog box, the 'add' button still says 'Get started!'.
kép


Proflle load doesn't select virtual module for removal.
virtual_selection


It's possible to create impossible layouts by removing modules in the middle.
kép

**Comment by elsoazemelet** [comment]
> In the dialog box, the 'add' button still says 'Get started!'. kép
> 
> Proflle load doesn't select virtual module for removal. virtual_selection [ virtual_selection ](https://private-user-images.githubusercontent.com/74784772/323623812-80b1446f-7d4f-4112-be78-cbbe252dbfd4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDIxOTksIm5iZiI6MTcxMzU0MTg5OSwicGF0aCI6Ii83NDc4NDc3Mi8zMjM2MjM4MTItODBiMTQ0NmYtN2Q0Zi00MTEyLWJlNzgtY2JiZTI1MmRiZmQ0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE1NTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYmM4NjA1YTllMzYyYzlkZjM2OTQyMTYwMjU2MmFkZTFmMzEzMjhiNDM2MzhhZWZmNzU0N2IyNzY2ZmZmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XJSd7m0SoeNGL8_X_ThBfGeOhYfcftCiO4aYzmIxO2g) [ ](https://private-user-images.githubusercontent.com/74784772/323623812-80b1446f-7d4f-4112-be78-cbbe252dbfd4.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM1NDIxOTksIm5iZiI6MTcxMzU0MTg5OSwicGF0aCI6Ii83NDc4NDc3Mi8zMjM2MjM4MTItODBiMTQ0NmYtN2Q0Zi00MTEyLWJlNzgtY2JiZTI1MmRiZmQ0LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDE1NTEzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyYmM4NjA1YTllMzYyYzlkZjM2OTQyMTYwMjU2MmFkZTFmMzEzMjhiNDM2MzhhZWZmNzU0N2IyNzY2ZmZmMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XJSd7m0SoeNGL8_X_ThBfGeOhYfcftCiO4aYzmIxO2g)
> 
> It's possible to create impossible layouts by removing modules in the middle. kép

Fixed in the latest commit! Please check new design proposel for the add module button!

**Comment by SukuWc** [comment]
Make hover hit-box larger
image

**Comment by SukuWc** [comment]
Also virutal module writeBuffer elements are never cleared, they just keep accumulating, please check using debug tools: 
image

**Comment by elsoazemelet** [comment]
All above is fixed in the latest commit

**Pull request merged**
