### PR TITLE
🚩PR: Various bugfixes and minor feature updates

### PR DESCRIPTION
**Pull request by elsoazemelet**
This PR is a collection of multiple minor bugfixes and feature updates. These are adequately described in their respective tickets. For more details check the tickets.

Closes the following tickets:

- #653 
- #655 
- #637 
- #652 
- #658 
- #672 
- #659 
- #654 

Also added features:

- More prominent drop shadow around control elements

### CODE REVIEW

**Comment by elsoazemelet** [comment]
Check print srceen and make issue form it

Képkivágás

**Comment by elsoazemelet** [comment]
- [x] Action picker should render to the middle of cursor if possible

**Comment by narayb** [comment]
## https://github.com/intechstudio/grid-editor/issues/653
Not completely fixed, when a context menu is active highlighting still works. even though highlighting should be disabled when the context menu is open, this is how it works on Windows.

Issue where opening the context menu makes the Editor window weirdly resize itself is also still active.


## https://github.com/intechstudio/grid-editor/issues/655
When copying not matching element, the overwrite option still appears in the context menu.

Context menu element copy doesn't work.
cntxt_bug

## https://github.com/intechstudio/grid-editor/issues/637
Creating a comment freezes Editor, breaks Code Block.
EDIT: ANY KIND OF CHANGE IN THE CODE BLOCK CAUSES THIS ERROR!
cmnt_bug


## extra
Drop shadow looks too much here on the 5 LEDs of the TEK2.
kép

**Comment by elsoazemelet** [comment]
> ## #653
> Not completely fixed, when a context menu is active highlighting still works. even though highlighting should be disabled when the context menu is open, this is how it works on Windows.
> 
> Issue where opening the context menu makes the Editor window weirdly resize itself is also still active.
> 
> ## #655
> When copying not matching element, the overwrite option still appears in the context menu.
> 
> Context menu element copy doesn't work. cntxt_bug [ cntxt_bug ](https://private-user-images.githubusercontent.com/74784772/323637136-ded9811e-5abe-4a05-bd41-434998d49fd2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzY2ODMsIm5iZiI6MTcxMzc3NjM4MywicGF0aCI6Ii83NDc4NDc3Mi8zMjM2MzcxMzYtZGVkOTgxMWUtNWFiZS00YTA1LWJkNDEtNDM0OTk4ZDQ5ZmQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MzU4N2Q2NGY2Nzc3ZjgyY2QxNWUyNzc0ODFjMzlkNDg0OTA3NGM3NzY2ZDU4YWQyZmRlOWVhMDI1ZTcwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tjTgtWgtXyDIJQ0phIAdIzRM6RcgX1EO18_0q-sf8n4) [ ](https://private-user-images.githubusercontent.com/74784772/323637136-ded9811e-5abe-4a05-bd41-434998d49fd2.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzY2ODMsIm5iZiI6MTcxMzc3NjM4MywicGF0aCI6Ii83NDc4NDc3Mi8zMjM2MzcxMzYtZGVkOTgxMWUtNWFiZS00YTA1LWJkNDEtNDM0OTk4ZDQ5ZmQyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE0MzU4N2Q2NGY2Nzc3ZjgyY2QxNWUyNzc0ODFjMzlkNDg0OTA3NGM3NzY2ZDU4YWQyZmRlOWVhMDI1ZTcwYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tjTgtWgtXyDIJQ0phIAdIzRM6RcgX1EO18_0q-sf8n4)
> 
> ## #637
> Creating a comment freezes Editor, breaks Code Block. EDIT: ANY KIND OF CHANGE IN THE CODE BLOCK CAUSES THIS ERROR! cmnt_bug [ cmnt_bug ](https://private-user-images.githubusercontent.com/74784772/323639412-aa2213e4-41f1-493d-9f4d-50463addb2e9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzY2ODMsIm5iZiI6MTcxMzc3NjM4MywicGF0aCI6Ii83NDc4NDc3Mi8zMjM2Mzk0MTItYWEyMjEzZTQtNDFmMS00OTNkLTlmNGQtNTA0NjNhZGRiMmU5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MmUwNmIzODY3YjJkN2I4MzEwOWYzMTZmZmExODBjNzk1YjFlMWI2ZWUzMDYyZWRkYmJkZDQyNWMwNjFiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0Re6KyUlWnsn31yAoaVFWZ_BgwfBEdMu-D-ftVm9cw) [ ](https://private-user-images.githubusercontent.com/74784772/323639412-aa2213e4-41f1-493d-9f4d-50463addb2e9.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzY2ODMsIm5iZiI6MTcxMzc3NjM4MywicGF0aCI6Ii83NDc4NDc3Mi8zMjM2Mzk0MTItYWEyMjEzZTQtNDFmMS00OTNkLTlmNGQtNTA0NjNhZGRiMmU5LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NTk0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2MmUwNmIzODY3YjJkN2I4MzEwOWYzMTZmZmExODBjNzk1YjFlMWI2ZWUzMDYyZWRkYmJkZDQyNWMwNjFiNzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y0Re6KyUlWnsn31yAoaVFWZ_BgwfBEdMu-D-ftVm9cw)
> 
> ## extra
> Drop shadow looks too much here on the 5 LEDs of the TEK2. kép

Fixed in the latest commit. 

- #653: The window resize is not apparent at my computer

**Comment by SukuWc** [comment]
Element overwrite in context menu is not disabled by default and gets disabled when an element is actually copied. The enable logic should be inverted!

**Comment by SukuWc** [comment]
Resolve conflicts

**Pull request merged**
