### PR TITLE
🚩PR: Multiple Virtual Modules can now be added

### LINKED ISSUE #651: Multiple module layout using virtual modules
- [ ] Add second module using button in developer options
- [ ] Remove second module using button in developer options
- [ ] Add button opens standard virtual module modal

### PR DESCRIPTION
**Pull request by elsoazemelet**
Closes #651 

The feature of adding multiple virtual modules is now added under developer settings.
The virtual modules can be added/removed by its coordinates. This reuses the virtual mode menu for module type selection when adding a new virtual module. 

- [ ] When the module under a certain coordinate does not exist, removing it should throw no error
- [ ] When a module already exist under a the coordinate you want to add another module, the module is replaced with the new one
- [ ] When connecting a physical module, all virtual modules should be destroyed

### CODE REVIEW

**Comment by elsoazemelet** [comment]
- [x] Add meaningful text in options
- [x] remove comments
- [x] implement BlockColumn in package and use it instead of divs
- [x] revert unintended commits

**Comment by narayb** [comment]
The change module button will always change the module in (0,0) position.
Therefore, it add a module to the (0,0) position when there is no (0,0) module.

multiple_vmodules


As both add and remove buttons add or remove the module as inputted into the developer settings, changing the modules should not be restricted to the module in the (0,0) position.

The three operations: add, remove and change should all follow the same logic.

**Comment by elsoazemelet** [comment]
> The change module button will always change the module in (0,0) position. Therefore, it add a module to the (0,0) position when there is no (0,0) module.
> 
> multiple_vmodules [ multiple_vmodules ](https://private-user-images.githubusercontent.com/74784772/319565542-1abace97-6c94-47d3-b710-c3a5d967ee82.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzExNjcsIm5iZiI6MTcxMjIzMDg2NywicGF0aCI6Ii83NDc4NDc3Mi8zMTk1NjU1NDItMWFiYWNlOTctNmM5NC00N2QzLWI3MTAtYzNhNWQ5NjdlZTgyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDExNDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNzk5ZDhmMmRjNGUxOGNmNjY2OGZiM2EwZTFkMDE1Yjg0YWUxMmQxZjk5YzRlMDJjODRjOWIyMzg1ZmQyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OuVNamfaZ3dj7i1Q-CIGvE-X9v5oI6C2EUijXxmaI14) [ ](https://private-user-images.githubusercontent.com/74784772/319565542-1abace97-6c94-47d3-b710-c3a5d967ee82.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIyMzExNjcsIm5iZiI6MTcxMjIzMDg2NywicGF0aCI6Ii83NDc4NDc3Mi8zMTk1NjU1NDItMWFiYWNlOTctNmM5NC00N2QzLWI3MTAtYzNhNWQ5NjdlZTgyLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA0VDExNDEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViNzk5ZDhmMmRjNGUxOGNmNjY2OGZiM2EwZTFkMDE1Yjg0YWUxMmQxZjk5YzRlMDJjODRjOWIyMzg1ZmQyZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.OuVNamfaZ3dj7i1Q-CIGvE-X9v5oI6C2EUijXxmaI14)
> 
> As both add and remove buttons add or remove the module as inputted into the developer settings, changing the modules should not be restricted to the module in the (0,0) position.
> 
> The three operations: add, remove and change should all follow the same logic.

This is not a valid use case, since the official release have and will have the feature of adding one module at the position of 0,0. The feature of officially being able to add multiple virtual modules will be introduced in the next developement cycle.

**Comment by narayb** [comment]
OK. Waiting until next implementation of this feature.

**Pull request merged**
