### PR TITLE
Fixed element overwrite change detection

### PR DESCRIPTION
**Pull request by elsoazemelet**
**As mentioned in discords #editor-qa channel:**

> "Init-en állítok egy led szín, utána whole element copy/overwrite segítségével másolnám többi elemre de az active change overlay az esetek nagyrészében nem triggerelődik"

**The issue was:**
Dumping configuration to a not yet fetched element (example: element overwrite) does not have a stored state, that is fetched when selecting the event, so there is nothing to be compared to when detecting active changes.

**Technical details of the fix:**
Fixed by reworking the event configuration fetching mechanism.
An event is always loaded before configurations can be sent to them.

### CODE REVIEW

**Comment by narayb** [comment]
Tested, still bugged.

Active changes only show up when the **target** of the enacted change is a **currently selected control element**.

## In case of profile/preset load
Active changes won't show up if the target of the **load doesn't match the currently selected element**. This will result is a profile being loaded, but only one control element lighting up in blue overlay, eve though the whole configuration changed.

## In case of overwrite
Active changes always show up when using overwrite, because **there is no way to overwrite without selecting the element first** you wish to overwrite.

**Comment by SukuWc** [comment]
Two PRs have been merged since, please merge stable into this branch!

**Comment by SukuWc** [comment]
tested with single PBF4, looks good. Still waiting for confirmation from @narayb !

**Comment by kkerti** [comment]
Tested with 1x EF44 + 1x PBF4, side by side.

Scenarios tested:
- [x] change control element init color, copy all, overwrite to other control elements (fader on pbf4)
- [x] change potmeter event (second event for triggering active change), copy all, overwrite to others (fader on pbf4)
- [x] move changed configuration from pbf4 to ef44, see appropiate events showing active changes
- [x] create element preset, no changes triggered
- [x] create module profile, no changes triggered
- [x] load element preset to appropriate element and see the active changes properly trigger
- [ ] after element preset is loaded, **THEN cleared**, new preset loads are not detected correctly

**Comment by kkerti** [comment]
> * [ ]  after element preset is loaded, **THEN cleared**, new preset loads are not detected correctly

Expanded steps to reproduce:
1. Change a control element's init color to something clearly visible
2. Create an element preset from it
3. Load this element preset to other control elements
4. Up until this point, active changes are working okay
5. **Clear** the module!
6. Reupload the element preset to control elements
7. **Active changes are not triggered anymore!**

Please fix.

https://github.com/intechstudio/grid-editor/assets/47832952/ae5bf9ab-ef76-40aa-ae3e-35f2985f7311

**Pull request merged**
