### PR TITLE
Suku preferences

### LINKED ISSUE #402: Preferences refactor to UI components
- [x] Vertical radio group
- [x] Horizontal radio group
- [x] DropDown
- [x] Checkbox
- [x] Text input
- [x] Button
- [x] Slider
- [x] Section Title
- [x] Section Text

### PR DESCRIPTION
**Pull request by SukuWc**

### CODE REVIEW

**Comment by SukuWc** [comment]
Notes for QA:
- [ ] Check analytics enable logic with fresh install (clean appsettings)
- [x] Check accessibility of preferences menu! (keyboard navigation using TAB, Shift+TAB, Space, Enter, Arrows)
- [x] Check for proper hover cursor usage (pointer)
- [x] Check an verify that preferences functionality is consistent with previous release
- [x] Check for visual bugs and responsible design (window size)

**Comment by narayb** [comment]
image
 Opening userdata folder causes an error message. String is probably confusing the slash or not reconizing it.

Checking checkboxes is done by the Space key and not by the Enter key, which could be confusing, since Space usually just jumps the panel scrollbar if you're on a selection that doesn't allow for "checking or unchecking a box". 
image

"Buttons" however use the Enter key and not the Space key for interacting with selected objects.
image

Selection is unable to "Tab over" to the next item from this textbox:
image


Probably not a real issue, but having inspector open combined with a narrow Editor window can break some of the text on the right side panel.
image

**Comment by narayb** [comment]
- [ ] Space and Enter on buttons and checkboxes consistency
- [ ] cannot tab into radio group when none of its options are selected

**Comment by narayb** [comment]
Fixes confirmed.
Space/Enter and focus lost on URL still not fixed.

**Pull request merged**
